version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank@123
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  bookstore:
    image: bookstore
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookstore
      SPRING_DATASOURCE_USERNAME: bank
      SPRING_DATASOURCE_PASSWORD: bank@123
    ports:
      - "8080:5000"
    command: ["java", "-jar", "/app/app.jar"]

volumes:
  postgres-data:
